#sudo: required
dist: trusty

language: python
python: 
  - 3.5

services:
  - postgresql
  - redis-server
#  - docker

addons:
  postgresql: "9.6"

#before_install:
#  - docker-compose -f docker-compose.yml up

install:
  - cd baa; pip install -r requirements.txt
  - pip install pytest
  - pip install codecov

script:
  - py.test

after_success:
  - codecovv
