#sudo: required
dist: trusty

language: python
python: 
  - 3.5

services:
  - postgresql
  - redis-server
#  - docker

addons:
  postgresql: "9.6"

#before_install:
#  - docker-compose -f docker-compose.yml up

install:
  - cd baa; pip install -r requirements.txt
  - pip install pytest
  - pip install codecov

#before_script:
#  - source ../env.example
script:
  - py.test

after_success:
  - codecovv

env:
  - SPOTIFY_CLIENT_ID="???" #adjust the '???' part for it to work
  - SPOTIFY_CLIENT_SECRET="???"
  - SPOTIFY_REDIRECT_URL="http://localhost:5000/callback"
  - SECRET_KEY="super secret key"
  - POSTGRES_URL="127.0.0.1:5432"
  - POSTGRES_USER="postgres"
  - POSTGRES_PW="dbpw"
  - POSTGRES_DB="test"
  - REDIS_URL="127.0.0.1:6379"
  - SENTRY_DNS="nope"
  - LC_ALL="C.UTF-8"
  - LANG="C.UTF-8"
