version: '2'

volumes:
  # for persistence between restarts and startup speed
  postgres_data: {}
  env: {}

services:
  db:
    #https://hub.docker.com/_/postgres/
    image: postgres:9.6.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
  redis:
    #https://hub.docker.com/_/redis/
    image: redis:3.2.9
  app:
    build: ./compose/app
    volumes:
      - ./baa:/srv/app
      - env:/srv/env
    working_dir: /srv/app
    env_file:
      - .env
    ports:
      - "127.0.0.1:9020:8000"
